name: CI Pipeline
on: [push]
jobs:
  Lint-Test-Build-Application:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/Iron'
      - run: echo "📦 Install Yarn"
      - run: npm install -g yarn
      - run: echo "📦 Install Dependencies"
      - run: yarn install
      - run: echo "🧪 Lint Code"
      - run: yarn run lint
      - run: echo "💉 Test Code"
      - run: yarn run test
      - run: echo "📦 Build Application"
      - run: yarn run build
