name: CI Pipeline
on: [push]
jobs:
  Lint-Test-Build-Application:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/Iron'
      - run: echo "📦 Install Dependencies"
      - run: npm install
      - run: echo "🧪 Lint Code"
      - run: npm run lint
      - run: echo "💉 Test Code"
      - run: npm run test
      - run: echo "📦 Build Application"
      - run: npm run build
